### ISSUE TITLE
Commenting breaks the app

### ISSUE THREAD

**Issue by derwiki** [civiccc/stars-causes#1]
No comment is left when I refresh the page.

**Comment by lencioni** [comment]
I just tried commenting on a star that was given to me and the card that contained my star was replaced with the following message: "We're sorry, but something went wrong. / We've been notified about this issue and we'll take a look at it shortly."

I think I can comment on stars that have been given to others.

**Comment by tdooner** [comment]
I think this is still a problem (sometimes?), as leaving a comment on a star given to me just 500'd:

```
Processing CommentsController#create (for 204.16.157.26 at 2014-01-29 15:58:37) [POST]
Sent mail to
  /usr/ruby1.9.2/lib/ruby/1.9.1/net/smtp.rb:866:in `rcptto'
  /usr/ruby1.9.2/lib/ruby/1.9.1/net/smtp.rb:923:in `getok'
Net::SMTPFatalError (555 5.5.2 Syntax error. w9sm213833qax.3 - gsmtp
):
  /usr/ruby1.9.2/lib/ruby/1.9.1/net/smtp.rb:526:in `start'
  /usr/ruby1.9.2/lib/ruby/1.9.1/net/smtp.rb:847:in `block in rcptto_list'
  .bundle/gems/ruby/1.9.1/gems/actionmailer-2.3.18/lib/action_mailer/base.rb:556:in `deliver!'
  .bundle/gems/ruby/1.9.1/gems/actionmailer-2.3.18/lib/action_mailer/base.rb:428:in `method_missing'
  /usr/ruby1.9.2/lib/ruby/1.9.1/net/smtp.rb:666:in `send_message'
  .bundle/gems/ruby/1.9.1/gems/actionmailer-2.3.18/lib/action_mailer/base.rb:717:in `block in perform_delivery_smtp'
  /usr/ruby1.9.2/lib/ruby/1.9.1/net/smtp.rb:845:in `each'
  app/models/comment.rb:7:in `block in <class:Comment>'

  .bundle/gems/ruby/1.9.1/gems/activesupport-2.3.18/lib/active_support/callbacks.rb:93:in `block in run'
  .bundle/gems/ruby/1.9.1/gems/activesupport-2.3.18/lib/active_support/callbacks.rb:92:in `each'
  .bundle/gems/ruby/1.9.1/gems/activesupport-2.3.18/lib/active_support/callbacks.rb:182:in `evaluate_method'
  .bundle/gems/ruby/1.9.1/gems/actionmailer-2.3.18/lib/action_mailer/base.rb:715:in `perform_delivery_smtp'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/callbacks.rb:267:in `create_with_callbacks'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/callbacks.rb:344:in `callback'
  /usr/ruby1.9.2/lib/ruby/1.9.1/net/smtp.rb:954:in `check_response'
  .bundle/gems/ruby/1.9.1/gems/activesupport-2.3.18/lib/active_support/callbacks.rb:276:in `run_callbacks'
  .bundle/gems/ruby/1.9.1/gems/activesupport-2.3.18/lib/active_support/callbacks.rb:182:in `call'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/base.rb:2935:in `create_or_update'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/validations.rb:1089:in `save_with_validation'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/base.rb:2585:in `save'
  .bundle/gems/ruby/1.9.1/gems/activesupport-2.3.18/lib/active_support/callbacks.rb:166:in `call'
  /usr/ruby1.9.2/lib/ruby/1.9.1/net/smtp.rb:845:in `rcptto_list'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/mime_responds.rb:106:in `respond_to'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/dirty.rb:79:in `save_with_dirty'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
  .bundle/gems/ruby/1.9.1/gems/activesupport-2.3.18/lib/active_support/callbacks.rb:92:in `run'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/transactions.rb:229:in `block in with_transaction_returning_status'
  <internal:prelude>:10:in `synchronize'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/dispatcher.rb:106:in `call'
  /home/heroku_rack/lib/static_assets.rb:9:in `call'
  /home/heroku_rack/lib/last_access.rb:15:in `call'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/callbacks.rb:250:in `create_or_update_with_callbacks'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/transactions.rb:196:in `save_with_transactions'
  app/controllers/comments_controller.rb:44:in `create'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/filters.rb:617:in `call_filters'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/transactions.rb:182:in `transaction'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/connection.rb:42:in `receive_data'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/backends/base.rb:57:in `start'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/server.rb:156:in `start'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/controllers/controller.rb:80:in `start'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/runner.rb:177:in `run_command'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/runner.rb:143:in `run!'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/bin/thin:6:in `<top (required)>'
  /usr/ruby1.9.2/bin/thin:19:in `load'
  /usr/ruby1.9.2/bin/thin:19:in `<main>'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/mime_responds.rb:106:in `call'
  app/controllers/comments_controller.rb:45:in `block in create'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/benchmarking.rb:68:in `block in perform_action_with_benchmark'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/filters.rb:610:in `perform_action_with_filters'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/rescue.rb:160:in `perform_action_with_rescue'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/base.rb:1333:in `perform_action'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/flash.rb:151:in `perform_action_with_flash'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/transactions.rb:196:in `block in save_with_transactions'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/filters.rb:606:in `process_with_filters'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/base.rb:386:in `call'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/base.rb:532:in `process'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/routing/route_set.rb:438:in `call'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/dispatcher.rb:87:in `dispatch'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/dispatcher.rb:121:in `_call'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/dispatcher.rb:130:in `block in build_middleware_stack'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/query_cache.rb:29:in `block in call'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/base.rb:391:in `process'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/query_cache.rb:9:in `cache'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/query_cache.rb:28:in `call'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/session/cookie_store.rb:99:in `call'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/params_parser.rb:15:in `call'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/string_coercion.rb:25:in `call'
  .bundle/gems/ruby/1.9.1/gems/hoptoad_notifier-2.4.11/lib/hoptoad_notifier/user_informer.rb:12:in `call'
  .bundle/gems/ruby/1.9.1/gems/actionpack-2.3.18/lib/action_controller/failsafe.rb:26:in `call'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/query_cache.rb:29:in `call'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/connection.rb:74:in `catch'
  .bundle/gems/ruby/1.9.1/gems/activerecord-2.3.18/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
  /home/heroku_rack/lib/date_header.rb:14:in `call'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/connection.rb:76:in `block in pre_process'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/connection.rb:74:in `pre_process'
  /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/thin-1.2.6/lib/thin/connection.rb:57:in `process'

  .bundle/gems/ruby/1.9.1/gems/hoptoad_notifier-2.4.11/lib/hoptoad_notifier/rack.rb:27:in `call'

Rendering /app/public/500.html (500 Internal Server Error)
```
